//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PearlDev
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Manufacture
    {
        public Manufacture()
        {
            this.Products = new HashSet<Products>();
        }
    
        public int ManuID { get; set; }
         [Display(Name = "Manufacture Name")]
        public string ManuName { get; set; }
    
        public virtual Manufacture Manufacture1 { get; set; }
        public virtual Manufacture Manufacture2 { get; set; }
        public virtual ICollection<Products> Products { get; set; }
    }
}
