//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PearlDev
{
    using System;
    using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
    
    public partial class Products
    {
        public int ProductID { get; set; }
         [Display(Name = "Name")]
        public string ProductName { get; set; }
         [Display(Name = "Manufacture")]
        public Nullable<int> ManufacturerID { get; set; }
         [Display(Name = "Manufucture Date")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> ManuDate { get; set; }
         [Display(Name = "Registration Date")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> RegistrationDate { get; set; }
         [Display(Name = "Photo")]
        public byte[] ProductImage { get; set; }
         [Display(Name = "Price")]
        public Nullable<decimal> ProductPrice { get; set; }
    
        public virtual Manufacture Manufacture { get; set; }
    }
}
